### ISSUE TITLE
Random prompt generated NSFW images

### ISSUE THREAD

**Issue by rtilghman96** [pixub/feedback#1]
Hello,

I was playing around with the generator, and the random prompt generated some NSFW images (though it included no NSFW words). I would suggest editing that feature so it limits or prohibits NSFW images entirely -- seeing as the prompt is random, users may get NSFW images they weren't asking for.

In fact, it seems as though your random prompt is always the same, and that it's prone to generate NSFW images. I'd update this prompt immediately to avoid any further unintentional NSFW images.

**Comment by fordnox** [comment]
Hi, removed random prompt to avoid this situation
